name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Ensure you're using the latest version

    - name: Set up QEMU
      uses: docker/setup-qemu-action@latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@latest

    - name: Login to DockerHub
      uses: docker/login-action@v2 # This action might have updated its method for outputting variables
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3 # This action should have updated its method for outputting variables
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: your_dockerhub_username/your_repo_name:latest
